### ISSUE TITLE
It seems it is currently unusable as a Python module.

### ISSUE THREAD

**Issue by KOLANICH** [konstin/pep440-rs#1]
Tried the example from the ReadMe:

`from pep440_rs import Version, VersionSpecifier`

got

* for a `cffi` version (when built without `pyo3` feature): `cannot import name 'Version' from 'pep440_rs'`
* for `pyo3` version for Python 3.9 (fixed `Cargo.toml` to build for it): `ModuleNotFoundError: No module named 'pep440_rs.pep440_rs'`. Replaced all occurences of `pep440_rs` within the file with the error with `_pep440_rs` - started working.

**Comment by konstin** [comment]
> (I'm using a pretty old version of Maturin (building it is nightmare), it can be that in newer one handles this better, but I had no issues with other packages about that)

pep440-rs requires maturin v0.14 as specified in pyproject.toml (`requires = ["maturin>=0.14,<0.15"]`). Patching in older versions is not supported. Is there any specific reason why you don't use the precompiled and signed maturin wheels we provide for x86_64 linux? Additionally, building from source shouldn't need more than pip and a standard rust installation.

When reporting problems in the future, please include the commands, versions and custom patches you used in the initial bug report.

> `sudo pip3 install --upgrade ./dist/pep440_rs-0.1.0-py3-none-linux_x86_64.whl`

Please don't use pip with sudo, that can mess badly with your os-installed packages

> BTW: the wheels are pretty large (because of cargo creating bloaty binaries by design), and they are even larger when contain debug symbols, which are not stripped by default.

There is are `--release` and `--strip` option in maturin for that we recommend using when publishing to pypi. A wheel produced this way is 551KB on my machine.

Calling `maturin build` manually is not intended for users but only for developers, where we trade faster compilation and debug symbols for larger files (and the compilation cache). Please refrain from making sweeping claims such as calling things "bloaty by design"; there are complex tradeoffs involved and low-key insulting the developers will not help your cause.

**Comment by KOLANICH** [comment]
Upgraded to maturin 14.3 (had to revert some commits).
`cffi` version still doesn't work.
`pyo3` version started working.

**Comment by KOLANICH** [comment]
>Please don't use pip with sudo, that can mess badly with your os-installed packages

This is intended.

>There is are --release and --strip option in maturin

For building packages we usually use PEP 517. Not only via `build` tool, but also via API (For example I am making a package manager for Python around building packages from source and not fetching anything from `pypi`). There are ways to provide additional args to build backends, but usually using `PEP 517` should produce optimized binaries.

>Is there any specific reason why you don't use the precompiled and signed maturin wheels we provide for x86_64 linux?

I usually stay away of PyPI. No reason relevant to Maturin. 

>Additionally, building from source shouldn't need more than pip and a standard rust installation.

I currently use a discontinued distro (Ubuntu 21.10) because Canonical got mad with its promotion of Snap. So the Rust version on the machine is `1.59`. I need to change the distro, but it hasn't be done yet. Despite Ubuntu is based on Debian, I have read in the Internet that just switching the repos will break my installation, so the migration is postponed.

**Comment by KOLANICH** [comment]
>Please don't use pip with sudo

Also, I have disabled fetching anything from `PyPI`, so installing a wheel via `sudo pip` will not cause anything be fetched and executed from root. Installing packages from root is very convenient, since these packages become immediately available for all OS users.
